model_name: "BloomZ-560M"
lora_rank: 16
learning_rate: 5e-5
batch_size: 32
num_epochs: 10
weight_decay: 0.01
max_seq_length: 512
gradient_accumulation_steps: 1
use_fp16: true
logging_steps: 100
save_steps: 500
evaluation_strategy: "steps"
output_dir: "./output"
seed: 42